// packages/svelte/src/screens/OAuthProviderButtons.svelte
<!--
  Copyright © 2026 Fells Code, LLC
  Licensed under the Apache License, Version 2.0
  See LICENSE file in the project root for full license information
-->
<!-- A button per OAuth provider the instance has enabled. Renders nothing without one. -->
<script lang="ts">
  import { startOAuthSignIn, type OAuthProvider } from '@seamless-auth/client';
  import { onMount } from 'svelte';

  import { getAuthNavigator, getSeamlessAuth } from '../context.js';

  /** The redirect URI to register with providers. Defaults to the bundled callback screen. */
  let { redirectUri }: { redirectUri?: string } = $props();

  const auth = getSeamlessAuth();
  const navigator = getAuthNavigator();
  let providers = $state.raw<OAuthProvider[]>([]);
  let error = $state('');

  onMount(async () => {
    const { data } = await auth.listOAuthProviders();
    providers = data?.providers ?? [];
  });

  async function select(providerId: string) {
    error = '';

    const result = await startOAuthSignIn(
      { actions: auth, oauthRedirect: auth.ports.oauthRedirect },
      { providerId, redirectUri: redirectUri ?? navigator.absoluteUrl('oauthCallback') }
    );

    if (result.error) error = result.error;
  }
</script>

{#if providers.length > 0}
  <div class="sa-actions">
    {#each providers as provider (provider.id)}
      <button type="button" class="sa-action" onclick={() => select(provider.id)}>
        <span class="sa-action-title">Continue with {provider.name}</span>
      </button>
    {/each}
    {#if error}
      <p class="sa-error">{error}</p>
    {/if}
  </div>
{/if}

// packages/angular/routes/src/oauth-provider-buttons.component.ts
/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the Apache License, Version 2.0
 * See LICENSE file in the project root for full license information
 */

import { ChangeDetectionStrategy, Component, inject, input, signal } from '@angular/core';
import { SeamlessAuth } from '@seamless-auth/angular';
import { startOAuthSignIn, type OAuthProvider } from '@seamless-auth/client';

import { injectAuthNavigation } from './navigation';
import { authRoutePaths } from './paths';

/** A button per OAuth provider the instance has enabled. Renders nothing without one. */
@Component({
  selector: 'sa-oauth-provider-buttons',
  template: `
    @if (providers().length > 0) {
      <div class="sa-actions">
        @for (provider of providers(); track provider.id) {
          <button type="button" class="sa-action" (click)="select(provider.id)">
            <span class="sa-action-title">Continue with {{ provider.name }}</span>
          </button>
        }
        @if (error()) {
          <p class="sa-error">{{ error() }}</p>
        }
      </div>
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SaOAuthProviderButtons {
  private readonly auth = inject(SeamlessAuth);
  private readonly navigation = injectAuthNavigation();

  /**
   * The redirect URI to register with providers. Defaults to the bundled
   * callback screen beside the screen this renders in.
   */
  readonly redirectUri = input<string>();

  readonly providers = signal<OAuthProvider[]>([]);
  readonly error = signal('');

  constructor() {
    void this.auth.listOAuthProviders().then(({ data }) => {
      this.providers.set(data?.providers ?? []);
    });
  }

  async select(providerId: string) {
    this.error.set('');

    const { error } = await startOAuthSignIn(
      { actions: this.auth, oauthRedirect: this.auth.ports.oauthRedirect },
      {
        providerId,
        redirectUri:
          this.redirectUri() ?? this.navigation.absoluteUrl(authRoutePaths.oauthCallback),
      }
    );

    if (error) {
      this.error.set(error);
    }
  }
}
