// packages/svelte/src/screens/MagicLinkSent.svelte
<!--
  Copyright © 2026 Fells Code, LLC
  Licensed under the Apache License, Version 2.0
  See LICENSE file in the project root for full license information
-->
<!--
  Waits for an emailed link to be used, then signs this tab in. A link opened in
  another tab of this browser reports back at once; one opened on another device
  is picked up by polling.
-->
<script lang="ts">
  import { MAGIC_LINK_RESEND_COOLDOWN_SECONDS, watchMagicLink } from '@seamless-auth/client';
  import { onMount } from 'svelte';

  import { getAuthNavigator, getSeamlessAuth } from '../context.js';
  import AuthLayout from './AuthLayout.svelte';

  const auth = getSeamlessAuth();
  const navigator = getAuthNavigator();
  const identifier = navigator.state().identifier as string | undefined;
  let cooldown = $state(MAGIC_LINK_RESEND_COOLDOWN_SECONDS);

  // Browser only: a server render must not poll or open a channel.
  onMount(() => {
    const timer = setInterval(() => {
      cooldown = Math.max(0, cooldown - 1);
    }, 1000);

    const stop = watchMagicLink({
      client: auth.client,
      refreshSession: auth.refreshSession,
      onSignedIn: () => void navigator.toApp(),
    });

    return () => {
      clearInterval(timer);
      stop();
    };
  });

  async function resend() {
    if (cooldown > 0) return;
    await auth.client.requestMagicLink();
    cooldown = MAGIC_LINK_RESEND_COOLDOWN_SECONDS;
  }
</script>

<AuthLayout>
  <div class="sa-center">
    <h2 class="sa-heading">Check your email</h2>
    <p class="sa-description">
      If an account exists for this address, we sent a secure sign-in link.
    </p>
    {#if identifier}
      <div class="sa-identifier">{identifier}</div>
    {/if}
    <p class="sa-helper-text">Open the email and click the link to finish signing in.</p>
    <p class="sa-helper-text">
      Didn't receive anything? Check your spam folder or try creating a new account.
    </p>
  </div>

  <div class="sa-actions">
    <button type="button" class="sa-secondary" disabled={cooldown > 0} onclick={resend}>
      Resend link
    </button>
    {#if cooldown > 0}
      <div class="sa-helper-text sa-center">Available in {cooldown}s</div>
    {/if}
    <button type="button" class="sa-link" onclick={() => navigator.toScreen('login')}>
      Change email or phone
    </button>
  </div>
</AuthLayout>

// packages/react/src/components/MagicLinkSent.tsx
/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the Apache License, Version 2.0
 * See LICENSE file in the project root for full license information
 */

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/AuthProvider';
import { useAuthClient } from '@/hooks/useAuthClient';
import { useNavigate, useLocation } from 'react-router-dom';

import {
  MAGIC_LINK_RESEND_COOLDOWN_SECONDS,
  watchMagicLink,
} from '@seamless-auth/client';

import styles from '@/styles/magiclink.module.css';

const MagicLinkSent: React.FC = () => {
  const { refreshSession } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const authClient = useAuthClient();

  const identifier = location.state?.identifier as string | undefined;

  const [cooldown, setCooldown] = useState(MAGIC_LINK_RESEND_COOLDOWN_SECONDS);

  useEffect(() => {
    const timer = setInterval(() => {
      setCooldown(c => (c > 0 ? c - 1 : 0));
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const resend = async () => {
    if (cooldown > 0) return;

    await authClient.requestMagicLink();

    setCooldown(MAGIC_LINK_RESEND_COOLDOWN_SECONDS);
  };

  useEffect(
    () =>
      watchMagicLink({
        client: authClient,
        refreshSession,
        onSignedIn: () => navigate('/'),
      }),
    [authClient, navigate, refreshSession]
  );

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <div className={styles.iconWrapper}>
          <div className={styles.iconRing}></div>

          <svg
            className={styles.mailIcon}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.8"
          >
            <path d="M4 6h16v12H4z" />
            <path d="m4 6 8 6 8-6" />
          </svg>
        </div>

        <h2 className={styles.heading}>Check your email</h2>

        <p className={styles.message}>
          If an account exists for this address, we sent a secure sign-in link.
        </p>

        {identifier && <div className={styles.identifier}>{identifier}</div>}

        <p className={styles.helperText}>
          Open the email and click the link to finish signing in.
        </p>

        <p className={styles.helperText}>
          Didn’t receive anything? Check your spam folder or try creating a new account.
        </p>

        <div className={styles.actions}>
          <button
            className={styles.secondaryButton}
            disabled={cooldown > 0}
            onClick={resend}
          >
            Resend link
          </button>

          {cooldown > 0 && (
            <div className={styles.cooldown}>Available in {cooldown}s</div>
          )}

          <button className={styles.linkButton} onClick={() => navigate('/login')}>
            Change email or phone
          </button>
        </div>
      </div>
    </div>
  );
};

export default MagicLinkSent;
