// packages/svelte/src/screens/Login.svelte
<!--
  Copyright © 2026 Fells Code, LLC
  Licensed under the Apache License, Version 2.0
  See LICENSE file in the project root for full license information
-->
<!-- Sign in with an email or phone number, or create an account with an email. -->
<script lang="ts">
  import {
    beginSignIn,
    isValidEmail,
    isValidPhoneNumber,
    PASSKEY_SIGN_IN_FAILED,
    registerWithEmail,
    type LoginMethod,
  } from '@seamless-auth/client';
  import { onMount } from 'svelte';

  import { getAuthNavigator, getSeamlessAuth } from '../context.js';
  import AuthLayout from './AuthLayout.svelte';
  import FallbackOptions from './FallbackOptions.svelte';
  import OAuthProviderButtons from './OAuthProviderButtons.svelte';

  const auth = getSeamlessAuth();
  const navigator = getAuthNavigator();

  // Opens on Sign In for a browser that has signed in before.
  let chosenMode = $state<'login' | 'register' | null>(null);
  const mode = $derived(chosenMode ?? (auth.hasSignedInBefore ? 'login' : 'register'));

  let identifier = $state('');
  let email = $state('');
  let identifierError = $state('');
  let emailError = $state('');
  let formError = $state('');
  let showFallbackOptions = $state(false);
  let loginMethods = $state.raw<LoginMethod[] | null>(null);
  let submitting = $state(false);

  const canSubmit = $derived(
    mode === 'login'
      ? isValidEmail(identifier) || isValidPhoneNumber(identifier)
      : // Registration only needs a valid email. A phone can be added later.
        isValidEmail(email)
  );

  // A disabled button is skipped by screen readers and explains nothing to
  // anyone else, so the reason it is refusing lives in a live region instead.
  const submitHint = $derived.by(() => {
    if (mode === 'login') {
      if (!identifier) return 'Enter your email or phone number to continue.';
      return canSubmit
        ? 'Ready to continue.'
        : 'This does not look like a complete email or phone number yet.';
    }

    if (!email) return 'Enter your email address to continue.';
    return canSubmit
      ? 'Ready to continue.'
      : 'This does not look like a complete email address yet.';
  });

  onMount(() => {
    void auth.loadLoginMethods();
    void auth.checkPasskeySupport();
  });

  function validateIdentifier() {
    if (!identifier) return;
    identifierError =
      isValidEmail(identifier) || isValidPhoneNumber(identifier)
        ? ''
        : 'Please enter a valid email or phone number';
  }

  function validateEmail() {
    if (!email) return;
    emailError = isValidEmail(email) ? '' : 'Please enter a valid email';
  }

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    if (!canSubmit || submitting) return;

    formError = '';
    showFallbackOptions = false;
    submitting = true;

    try {
      if (mode === 'register') {
        const { error } = await registerWithEmail(auth.client, email);

        if (error) {
          formError = error;
          return;
        }

        await navigator.toScreen('verifyEmailOtp');
        return;
      }

      // Both are cached, so awaiting them costs nothing once loaded and removes
      // the race where a fast submit saw passkeys as unsupported.
      const [passkeySupported, configuredMethods] = await Promise.all([
        auth.checkPasskeySupport(),
        auth.loadLoginMethods(),
      ]);

      const step = await beginSignIn(auth, { identifier, passkeySupported, configuredMethods });

      if (step.kind === 'error') {
        formError = step.message;
        return;
      }

      if (step.kind === 'signed_in') {
        await navigator.toApp();
        return;
      }

      loginMethods = step.loginMethods;
      showFallbackOptions = true;

      if (step.passkeyFailed) formError = PASSKEY_SIGN_IN_FAILED;
    } catch {
      // Backstop for unexpected errors only. The client reports request
      // failures through `error`, not by throwing.
      formError = 'Failed to continue sign-in. Please try again.';
    } finally {
      submitting = false;
    }
  }

  async function retryPasskey() {
    formError = '';
    const { error } = await auth.handlePasskeyLogin();

    if (error) {
      formError = PASSKEY_SIGN_IN_FAILED;
      return;
    }

    await navigator.toApp();
  }

  async function sendMagicLink() {
    const { error } = await auth.client.requestMagicLink();

    if (error) {
      formError = 'Failed to send magic link.';
      return;
    }

    await navigator.toScreen('magicLinkSent', { identifier });
  }

  async function sendEmailOtp() {
    const { error } = await auth.client.requestLoginEmailOtp();

    if (error) {
      formError = 'Failed to send email code.';
      return;
    }

    await navigator.toScreen('verifyEmailOtp', { flow: 'login' });
  }

  async function sendPhoneOtp() {
    const { error } = await auth.client.requestLoginPhoneOtp();

    if (error) {
      formError = 'Failed to send OTP.';
      return;
    }

    await navigator.toScreen('verifyPhoneOtp', { flow: 'login' });
  }
</script>

<AuthLayout>
  <h2 class="sa-heading">{mode === 'login' ? 'Sign In' : 'Create Account'}</h2>

  <form onsubmit={submit}>
    {#if mode === 'login'}
      <div class="sa-input-group">
        <label for="identifier" class="sa-label">Email Address / Phone Number</label>
        <input
          id="identifier"
          type="text"
          class="sa-input"
          autocomplete="off"
          placeholder="Email or Phone Number"
          required
          bind:value={identifier}
          onblur={validateIdentifier}
        />
        <p class="sa-helper-text">Phone numbers must include a country code e.g. +1</p>

        {#if showFallbackOptions}
          <FallbackOptions
            {identifier}
            {loginMethods}
            onMagicLink={sendMagicLink}
            onEmailOtp={sendEmailOtp}
            onPhoneOtp={sendPhoneOtp}
            onPasskeyRetry={auth.passkeySupported ? retryPasskey : undefined}
          />
        {/if}

        {#if identifierError}
          <p class="sa-error">{identifierError}</p>
        {/if}
      </div>
    {:else}
      <div class="sa-input-group">
        <label for="email" class="sa-label">Email Address</label>
        <input
          id="email"
          type="email"
          class="sa-input"
          autocomplete="off"
          required
          bind:value={email}
          onblur={validateEmail}
        />
        {#if emailError}
          <p class="sa-error">{emailError}</p>
        {/if}
      </div>
    {/if}

    <button
      type="submit"
      class="sa-button"
      disabled={!canSubmit || submitting}
      aria-describedby="seamless-submit-hint"
    >
      {mode === 'login' ? 'Login' : 'Register'}
    </button>
    <p id="seamless-submit-hint" role="status" class="sa-submit-hint">{submitHint}</p>
    {#if formError}
      <p class="sa-error">{formError}</p>
    {/if}
    <button
      type="button"
      class="sa-link"
      onclick={() => (chosenMode = mode === 'login' ? 'register' : 'login')}
    >
      {mode === 'login' ? "Don't have an account? Create one" : 'Already have an account? Sign in'}
    </button>
  </form>

  <OAuthProviderButtons />
</AuthLayout>

// src/views/Login.tsx
/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */

import { useAuth } from '@/AuthProvider';
import React, { useEffect, useState } from 'react';
import { useAuthClient } from '@/hooks/useAuthClient';
import { usePasskeySupport } from '@/hooks/usePasskeySupport';
import { useNavigate } from 'react-router-dom';
import { authRoutePaths } from '@/routes';
import styles from '@/styles/login.module.css';
import { isValidEmail, isValidPhoneNumber } from '../utils';
import AuthFallbackOptions from '@/components/AuthFallbackOptions';
import OAuthProviderButtons from '@/components/OAuthProviderButtons';
import type { LoginMethod } from '@/client/createSeamlessAuthClient';

const DEFAULT_LOGIN_METHODS: LoginMethod[] = ['passkey', 'magic_link', 'phone_otp'];

const Login: React.FC = () => {
  const navigate = useNavigate();
  const { hasSignedInBefore, login, handlePasskeyLogin } = useAuth();
  const authClient = useAuthClient();
  const { passkeySupported } = usePasskeySupport();
  const [identifier, setIdentifier] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [mode, setMode] = useState<'login' | 'register'>('register');
  const [formErrors, setFormErrors] = useState<string>('');
  const [emailError, setEmailError] = useState<string>('');
  const [identifierError, setIdentifierError] = useState<string>('');
  const [showFallbackOptions, setShowFallbackOptions] = useState(false);
  const [loginMethods, setLoginMethods] = useState<LoginMethod[]>(DEFAULT_LOGIN_METHODS);
  const [bootstrapToken, setBootstrapToken] = useState<string | null>(null);

  useEffect(() => {
    if (hasSignedInBefore) {
      setMode('login');
    }

    const params = new URLSearchParams(window.location.search);
    const token = params.get('bootstrapToken');

    if (token && token.length > 10) {
      setBootstrapToken(token);
    }
  }, [hasSignedInBefore]);

  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const email = e.target.value;
    setEmail(email);
  };

  const handleIdentifierChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setIdentifier(value);
  };

  const canSubmit = (): boolean | undefined => {
    if (mode === 'login' && identifier) {
      return isValidEmail(identifier) || isValidPhoneNumber(identifier);
    }

    // Registration only needs a valid email. A phone can be added later.
    return isValidEmail(email);
  };

  const register = async () => {
    setFormErrors('');

    const { data, error } = await authClient.register({
      email,
      bootstrapToken,
    });

    if (error) {
      setFormErrors('Failed to register. Please try again.');
      return;
    }

    if (data.message !== 'Success') {
      setFormErrors(
        'An unexpected error occurred. Try again. If the problem persists, contact support.'
      );
      return;
    }

    navigate(authRoutePaths.verifyEmailOtp);
  };

  const sendMagicLink = async () => {
    const { error } = await authClient.requestMagicLink();

    if (error) {
      setFormErrors('Failed to send magic link.');
      return;
    }

    navigate(authRoutePaths.magicLinkSent, { state: { identifier } });
  };

  const sendPhoneOtp = async () => {
    const { error } = await authClient.requestLoginPhoneOtp();

    if (error) {
      setFormErrors('Failed to send OTP.');
      return;
    }

    navigate(authRoutePaths.verifyPhoneOtp, { state: { flow: 'login' } });
  };

  const sendEmailOtp = async () => {
    const { error } = await authClient.requestLoginEmailOtp();

    if (error) {
      setFormErrors('Failed to send email code.');
      return;
    }

    navigate(authRoutePaths.verifyEmailOtp, { state: { flow: 'login' } });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setFormErrors('');
    setShowFallbackOptions(false);

    try {
      if (mode === 'login') {
        const { data: loginStart, error } = await login(identifier, passkeySupported);

        if (error) {
          setFormErrors('Failed to start sign-in. Please try again.');
          return;
        }

        const availableMethods = loginStart?.loginMethods?.length
          ? loginStart.loginMethods
          : DEFAULT_LOGIN_METHODS;
        setLoginMethods(availableMethods);

        if (passkeySupported && availableMethods.includes('passkey')) {
          const { error: passkeyError } = await handlePasskeyLogin();

          if (!passkeyError) {
            navigate('/');
            return;
          }

          setShowFallbackOptions(true);
          setFormErrors(
            'Passkey sign-in could not be completed. Choose another sign-in method.'
          );
          return;
        }

        setShowFallbackOptions(true);
        return;
      }

      if (mode === 'register') {
        await register();
      }
    } catch {
      // Backstop for unexpected errors only. The client reports request
      // failures through `error`, not by throwing.
      console.error('Failed to continue sign-in.');
      setFormErrors('Failed to continue sign-in. Please try again.');
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h2 className={styles.heading}>
          {mode === 'login' ? 'Sign In' : 'Create Account'}
        </h2>

        <>
          <form onSubmit={handleSubmit}>
            {mode === 'login' && (
              <div className={styles.inputGroup}>
                <label htmlFor="identifier" className={styles.label}>
                  Email Address / Phone Number
                </label>
                <input
                  id="identifier"
                  type="text"
                  value={identifier}
                  onChange={handleIdentifierChange}
                  autoComplete="off"
                  placeholder="Email or Phone Number"
                  className={styles.input}
                  onBlur={() => {
                    if (identifier) {
                      const isValid =
                        isValidEmail(identifier) || isValidPhoneNumber(identifier);
                      setIdentifierError(
                        isValid ? '' : 'Please enter a valid email or phone number'
                      );
                    }
                  }}
                  required
                />
                <p className={styles.helperText}>
                  Phone numbers must include a country code e.g. +1
                </p>
                {showFallbackOptions && (
                  <AuthFallbackOptions
                    identifier={identifier}
                    onMagicLink={sendMagicLink}
                    onEmailOtp={sendEmailOtp}
                    onPhoneOtp={sendPhoneOtp}
                    onPasskeyRetry={passkeySupported ? handlePasskeyLogin : undefined}
                    loginMethods={loginMethods}
                  />
                )}

                {identifierError && <p className={styles.error}>{identifierError}</p>}
              </div>
            )}
            {mode === 'register' && (
              <div className={styles.inputGroup}>
                <label htmlFor="email" className={styles.label}>
                  Email Address
                </label>
                <input
                  id="email"
                  type="email"
                  value={email}
                  onChange={handleEmailChange}
                  autoComplete="off"
                  className={styles.input}
                  onBlur={() => {
                    if (email) {
                      const isValid = isValidEmail(email);
                      setEmailError(isValid ? '' : 'Please enter a valid email');
                    }
                  }}
                  required
                />
                {emailError && <p className={styles.error}>{emailError}</p>}
              </div>
            )}
            <button type="submit" className={styles.button} disabled={!canSubmit()}>
              {mode === 'login' ? 'Login' : 'Register'}
            </button>
            {formErrors && <p className={styles.error}>{formErrors}</p>}
            <button
              type="button"
              onClick={() => setMode(mode === 'login' ? 'register' : 'login')}
              className={styles.toggle}
            >
              {mode === 'login'
                ? "Don't have an account? Create one"
                : 'Already have an account? Sign in'}
            </button>
          </form>

          <OAuthProviderButtons />
        </>
      </div>
    </div>
  );
};

export default Login;
