// packages/svelte/src/screens/OAuthProviderButtons.svelte
<!--
  Copyright © 2026 Fells Code, LLC
  Licensed under the Apache License, Version 2.0
  See LICENSE file in the project root for full license information
-->
<!-- A button per OAuth provider the instance has enabled. Renders nothing without one. -->
<script lang="ts">
  import { startOAuthSignIn, type OAuthProvider } from '@seamless-auth/client';
  import { onMount } from 'svelte';

  import { getAuthNavigator, getSeamlessAuth } from '../context.js';

  /** The redirect URI to register with providers. Defaults to the bundled callback screen. */
  let { redirectUri }: { redirectUri?: string } = $props();

  const auth = getSeamlessAuth();
  const navigator = getAuthNavigator();
  let providers = $state.raw<OAuthProvider[]>([]);
  let error = $state('');

  onMount(async () => {
    const { data } = await auth.listOAuthProviders();
    providers = data?.providers ?? [];
  });

  async function select(providerId: string) {
    error = '';

    const result = await startOAuthSignIn(
      { actions: auth, oauthRedirect: auth.ports.oauthRedirect },
      { providerId, redirectUri: redirectUri ?? navigator.absoluteUrl('oauthCallback') }
    );

    if (result.error) error = result.error;
  }
</script>

{#if providers.length > 0}
  <div class="sa-actions">
    {#each providers as provider (provider.id)}
      <button type="button" class="sa-action" onclick={() => select(provider.id)}>
        <span class="sa-action-title">Continue with {provider.name}</span>
      </button>
    {/each}
    {#if error}
      <p class="sa-error">{error}</p>
    {/if}
  </div>
{/if}

// src/components/OAuthProviderButtons.tsx
/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/AuthProvider';
import type { OAuthProvider } from '@/client/createSeamlessAuthClient';

import styles from '../styles/login.module.css';

export const OAUTH_PROVIDER_STORAGE_KEY = 'seamless:oauth:provider';

const OAuthProviderButtons: React.FC = () => {
  const { listOAuthProviders, startOAuthLogin } = useAuth();
  const [providers, setProviders] = useState<OAuthProvider[]>([]);
  const [error, setError] = useState('');

  useEffect(() => {
    let active = true;

    listOAuthProviders()
      .then(result => {
        if (active) setProviders(result.providers ?? []);
      })
      .catch(() => {
        if (active) setProviders([]);
      });

    return () => {
      active = false;
    };
  }, [listOAuthProviders]);

  if (providers.length === 0) {
    return null;
  }

  const handleSelect = async (providerId: string) => {
    setError('');
    try {
      // The callback route reads this to know which provider to finish with.
      sessionStorage.setItem(OAUTH_PROVIDER_STORAGE_KEY, providerId);

      const { authorizationUrl } = await startOAuthLogin({
        providerId,
        redirectUri: `${window.location.origin}/oauth/callback`,
      });

      window.location.assign(authorizationUrl);
    } catch {
      setError('Could not start sign-in with this provider.');
    }
  };

  return (
    <div className={styles.fallbackActions}>
      {providers.map(provider => (
        <button
          key={provider.id}
          type="button"
          className={styles.fallbackActionButton}
          onClick={() => handleSelect(provider.id)}
        >
          <span className={styles.actionTitle}>Continue with {provider.name}</span>
        </button>
      ))}

      {error && <p className={styles.error}>{error}</p>}
    </div>
  );
};

export default OAuthProviderButtons;
