// src/views/VerifyMagicLink.tsx
/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/AuthProvider';
import { useAuthClient } from '@/hooks/useAuthClient';
import { useNavigate, useSearchParams } from 'react-router-dom';

import styles from '@/styles/verifyMagiclink.module.css';

const VerifyMagicLink: React.FC = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const token = searchParams.get('token');

  const [error, setError] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  const authClient = useAuthClient();
  const { refreshSession } = useAuth();

  useEffect(() => {
    let mounted = true;
    let channel: BroadcastChannel | null = null;
    let redirectTimeout: ReturnType<typeof setTimeout> | null = null;

    const verify = async () => {
      if (!token) {
        if (mounted) {
          setError('Missing token for verification.');
        }
        console.error('No magic-link token found.');
        return;
      }

      try {
        const response = await authClient.verifyMagicLink(token);

        if (!response.ok) {
          console.error('Failed to verify token');
          if (mounted) {
            setError('Failed to verify token');
          }
          return;
        }

        // The verify call sets the session cookie for this browser. Sync
        // provider state here so the tab that completed verification lands
        // authenticated instead of relying on another tab or a manual reload.
        await refreshSession();
      } catch {
        console.error('Failed to verify magic-link token.');
      }

      if (!mounted) {
        return;
      }

      channel = new BroadcastChannel('seamless-auth');

      channel.postMessage({
        type: 'MAGIC_LINK_AUTH_SUCCESS',
      });

      setSuccessMsg(
        'You have been verified on the device and browser that initiated this request'
      );

      redirectTimeout = setTimeout(() => {
        if (!mounted) {
          return;
        }

        navigate('/');
      }, 900);
    };
    verify();

    return () => {
      mounted = false;
      channel?.close();

      if (redirectTimeout) {
        clearTimeout(redirectTimeout);
      }
    };
  }, [token, authClient, navigate, refreshSession]);

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h1 className={styles.title}>Verifying your login</h1>

        <div className={styles.verificationContent}>
          {!successMsg && !error && <div className={styles.spinner}></div>}

          {successMsg && (
            <div className={styles.successIcon}>
              <svg
                viewBox="0 0 24 24"
                className={styles.checkIcon}
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M5 13l4 4L19 7" />
              </svg>
            </div>
          )}

          {!successMsg && !error && (
            <p className={styles.helperText}>
              Please wait while we securely verify your sign-in link.
            </p>
          )}

          {successMsg && (
            <p className={styles.successText}>Login verified. Redirecting…</p>
          )}

          {error && <p className={styles.error}>{error}</p>}
        </div>
      </div>
    </div>
  );
};

export default VerifyMagicLink;

// packages/svelte/src/screens/VerifyMagicLink.svelte
<!--
  Copyright © 2026 Fells Code, LLC
  Licensed under the Apache License, Version 2.0
  See LICENSE file in the project root for full license information
-->
<!--
  Where an emailed magic link lands. Verifies the link once, tells the tab that
  asked for it, and signs this tab in too when the link was opened in the same
  browser.
-->
<script lang="ts">
  import { finishMagicLinkSignIn, type MagicLinkOutcome } from '@seamless-auth/client';
  import { onMount } from 'svelte';

  import { getAuthNavigator, getSeamlessAuth } from '../context.js';
  import AuthLayout from './AuthLayout.svelte';

  const auth = getSeamlessAuth();
  const navigator = getAuthNavigator();
  let outcome = $state<MagicLinkOutcome | null>(null);
  let error = $state('');

  // Browser only. A server render would spend the single-use link in a request
  // that carries none of this browser's cookies.
  onMount(() => {
    let active = true;
    let redirect: ReturnType<typeof setTimeout> | undefined;

    void (async () => {
      const token = navigator.query('token');

      if (!token) {
        error = 'Missing token for verification.';
        return;
      }

      // The token is read; keep it out of history and Referers from here on.
      void navigator.dropQuery();

      // A link can be used once, and a mounted screen verifies it once.
      const result = await auth.client.verifyMagicLink(token);

      if (!active) return;

      if (result.error) {
        error = 'Failed to verify token';
        return;
      }

      const next = await finishMagicLinkSignIn({
        client: auth.client,
        refreshSession: auth.refreshSession,
      });

      if (!active) return;

      outcome = next;

      if (next === 'signed-in') {
        redirect = setTimeout(() => void navigator.toApp(), 900);
      }
    })();

    return () => {
      active = false;
      clearTimeout(redirect);
    };
  });
</script>

<AuthLayout>
  <div class="sa-center">
    <h1 class="sa-heading">Verifying your login</h1>

    {#if !outcome && !error}
      <div class="sa-spinner" aria-hidden="true"></div>
      <p class="sa-helper-text">Please wait while we securely verify your sign-in link.</p>
    {/if}
    {#if outcome === 'signed-in'}
      <p class="sa-success" role="status">Login verified. Redirecting...</p>
    {/if}
    {#if outcome === 'elsewhere'}
      <p class="sa-success" role="status">
        Login verified. Return to the device where you requested this link to continue.
      </p>
    {/if}
    {#if error}
      <p class="sa-error" role="alert">{error}</p>
    {/if}
  </div>
</AuthLayout>
